base_clearance_fee: 3100
base_util_fee: 20000
etc_util_coeff_base: 1.0
ctp_util_coeff_base: 1.2
excise_rates:
  gasoline: 58
  diesel: 58
  electric: 0
  hybrid: 58
recycling_factors:
  default:
    gasoline: 1.0
    diesel: 1.1
    electric: 0.3
    hybrid: 1.0
  adjustments:
    "5-7":
      gasoline: 0.26
      diesel: 0.26
      electric: 0.26
      hybrid: 0.26
age_groups:
  new:
    gasoline:
      rate_per_cc: 2.5
      min_duty: 0
    diesel:
      rate_per_cc: 2.7
      min_duty: 0
    electric:
      rate_per_cc: 0
      min_duty: 1000
    hybrid:
      rate_per_cc: 1.8
      min_duty: 2000
  "1-3":
    gasoline:
      rate_per_cc: 3.0
      min_duty: 0
    diesel:
      rate_per_cc: 3.2
      min_duty: 0
    electric:
      rate_per_cc: 0
      min_duty: 1000
    hybrid:
      rate_per_cc: 2.0
      min_duty: 2000
  "3-5":
    gasoline:
      rate_per_cc: 4.0
      min_duty: 0
    diesel:
      rate_per_cc: 4.2
      min_duty: 0
    electric:
      rate_per_cc: 0
      min_duty: 1000
    hybrid:
      rate_per_cc: 2.5
      min_duty: 2500
  "5-7":
    gasoline:
      rate_per_cc: 4.8
      min_duty: 0
    diesel:
      rate_per_cc: 5.0
      min_duty: 0
    electric:
      rate_per_cc: 0
      min_duty: 1000
    hybrid:
      rate_per_cc: 2.0
      min_duty: 2500
  over_7:
    gasoline:
      rate_per_cc: 5.5
      min_duty: 0
    diesel:
      rate_per_cc: 5.8
      min_duty: 0
    electric:
      rate_per_cc: 0
      min_duty: 1000
    hybrid:
      rate_per_cc: 3.0
      min_duty: 3000
vat_rate: 0.2
